name = input("Enter your name")
age = input("Enter your age")
dept = input("Enter your department")
email = input("Enter your email")
phone = input("Enter your phone number")

print("----------------------------------")
print("     STUDENT REGISTRATION")
print("----------------------------------")
print("Welcome John")
print("You have successfully registered.")
print("Department:")
print("Computer Science")
print("Email:")
print("john@gmail.com")
