str1 = ("Jochebed Sabonruwa")
num1 = ("18")
str2 = ("Computer Science Department")
str3 = ("Air Force Institute of Technology(AFIT), Kaduna")
str4 = ("200 Level")
str5 = ("Adamawa State")
str6 = ("Pink")
str7 = ("Jollof Rice")

print("My name is ", str1)
print("I am ", num1, "years old")
print("I am a student of ", str2)
print("I attend ", str3)
print("I am in ", str4)
print("I hail from ", str5)
print("My favorite color is ", str6)
print("My favorite food is", str7)